#@data/values
---
namespace:
  name: educateshub
  create: true
replicas: 1
image:
  name: ghcr.io/educates/educates-hub:main
  build: false
  push_repo: registry.test:5000/educates #! DO NOT SPECIFY TAG
host: hub.10.30.82.22.nip.io
dockerfile: docker/Dockerfile.innerloop
portals:
  - name: educates-training-portal-ui-failk8s-dev
    url: https://educates-training-portal-ui.training.failk8s.dev
    robot:
      client_id: grumpy-old-man
      client_secret: what-a-looser
      username: robot@educates
      password: jorge-is-awesome
  - name: educates-training-portal-ui-failk8s-com
    url: https://educates-training-portal-ui.training.failk8s.com
    robot:
      client_id: grumpy-old-man
      client_secret: what-a-looser
      username: robot@educates
      password: jorge-is-awesome
  - name: lab-spring-boot-ui-failk8s-dev
    url: https://lab-spring-boot-ui.training.failk8s.dev
    robot:
      client_id: grumpy-old-man
      client_secret: what-a-looser
      username: robot@educates
      password: jorge-is-awesome
